modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="golden_meadows"
version="1.0"
displayName="Golden Meadows"
displayURL="https://www.curseforge.com/members/smartstreamlabs/projects"
logoFile="logo.png"
credits="SmartStreamLabs"
authors="SmartStreamLabs"
description="Beautiful Biome & Dimension for the quiet life"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.golden_meadows]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.101-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.golden_meadows]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration